### ISSUE TITLE
What's the next big thing in terms of Social Media happening in 2017?

### ISSUE THREAD

**Issue by miduga** [manovotny/ama#1]
I see that there's a lot of movement regarding Live Video Streaming but, in your opinion, what's the next big thing for Social Media for next year? Is there some low-profile app that could get an amazing traction in 2017 with a new idea? Thanks!

**Comment by manovotny** [comment]
Oh gosh... I am *far* from a social media expert. I'd probably barely qualify as a casual user.

However, I am good friends with [Justin Wise](https://twitter.com/JustinWise) who is a a social media pro. 

I passed along your question to him and here's what he had to say.

> Next big thing? Dark Social. Social media platforms that don't have a public-facing element: a la Snapchat, Instagram stories, WeChat, etc.
> 
> Also, check this post out:
> 
> http://chrissniderdesign.com/blog/2016/10/20/class-2020-thinks-social-media/

Thanks for the question, @miduga! Hope that is an adequate answer for you.
