### ISSUE TITLE
How To Fix WordPress Admin Styles Not Loading

### ISSUE THREAD

**Issue by omlarsen** [manovotny/ama#2]
Hi!
I have tried your suggestion to change in wp-admin/load-styles.php and  wp-config.php file.
I still have problems. Screenshot: http://verdalsportalen.no/FraTore/ControlPanelWordpress.JPG
I have louded it from one.com.     verdalsportalen.no   omlarsen/obamacarE230317 
Ole Morten Larsen

**Comment by omlarsen** [comment]
ok now

**Comment by manovotny** [comment]
Glad you got it all worked out, @omlarsen!
