### ISSUE TITLE
WPtest.io content

### ISSUE THREAD

**Issue by dimitrimoderbacher** [manovotny/ama#3]
Hello Michael,

My name is Dimitri. I live in Brooklyn. I've been trying to get deeper into Wordpress. 

I just recently came across wptest.io, it's a great tool! I downloaded the demo but the demo content doesn't match the demo on http://wptest.io/demo/
Is there a way to download that version of WP Test Demo (particularly all the bullets in "Test These Things")?

Please, forgive me if that is something you don't want to share or if that's something I'm not supposed to ask for. 

Thanks!
Dimitri

**Comment by dimitrimoderbacher** [comment]
oh, wait, I'm sorry. I figured out that the "Test These Things" section contained links to posts as well as pages. Thanks for all your hard work!
Dimitri

**Comment by manovotny** [comment]
Hey @dimitrimoderbacher! Thanks for the comment.

Actually, I am no longer the owner of WP Test. I "sold" it to Post Status, which you can read more about in [this post from them](https://poststatus.com/notes/new-wptest-io/).
