### ISSUE TITLE
Did you grow up in Chicago?

### ISSUE THREAD

**Issue by TonyGravagno** [manovotny/ama#4]
Or is your family on the north side? I recall a Novotny family from "way back"...

**Comment by manovotny** [comment]
Hey @TonyGravagno! 👋 

No, I didn't grow up in Chicago. I grew up in eastern Iowa. My dad was an only child, and so was his dad, and they both grew up in eastern Iowa too. So... Not a lot of lineage in our branch of the Novotny family tree, but I'm sure there is some relation down the line somewhere. It's a not a very common name. 

Thanks for the question though!
